//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceConsumerHello.HelloService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HelloService.HelloWorldSoap")]
    public interface HelloWorldSoap {
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SayHello", ReplyAction="*")]
        ServiceConsumerHello.HelloService.SayHelloResponse SayHello(ServiceConsumerHello.HelloService.SayHelloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SayHello", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceConsumerHello.HelloService.SayHelloResponse> SayHelloAsync(ServiceConsumerHello.HelloService.SayHelloRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SayHelloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SayHello", Namespace="http://tempuri.org/", Order=0)]
        public ServiceConsumerHello.HelloService.SayHelloRequestBody Body;
        
        public SayHelloRequest() {
        }
        
        public SayHelloRequest(ServiceConsumerHello.HelloService.SayHelloRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SayHelloRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public SayHelloRequestBody() {
        }
        
        public SayHelloRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SayHelloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SayHelloResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceConsumerHello.HelloService.SayHelloResponseBody Body;
        
        public SayHelloResponse() {
        }
        
        public SayHelloResponse(ServiceConsumerHello.HelloService.SayHelloResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SayHelloResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SayHelloResult;
        
        public SayHelloResponseBody() {
        }
        
        public SayHelloResponseBody(string SayHelloResult) {
            this.SayHelloResult = SayHelloResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HelloWorldSoapChannel : ServiceConsumerHello.HelloService.HelloWorldSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HelloWorldSoapClient : System.ServiceModel.ClientBase<ServiceConsumerHello.HelloService.HelloWorldSoap>, ServiceConsumerHello.HelloService.HelloWorldSoap {
        
        public HelloWorldSoapClient() {
        }
        
        public HelloWorldSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HelloWorldSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloWorldSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloWorldSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceConsumerHello.HelloService.SayHelloResponse ServiceConsumerHello.HelloService.HelloWorldSoap.SayHello(ServiceConsumerHello.HelloService.SayHelloRequest request) {
            return base.Channel.SayHello(request);
        }
        
        public string SayHello(string name) {
            ServiceConsumerHello.HelloService.SayHelloRequest inValue = new ServiceConsumerHello.HelloService.SayHelloRequest();
            inValue.Body = new ServiceConsumerHello.HelloService.SayHelloRequestBody();
            inValue.Body.name = name;
            ServiceConsumerHello.HelloService.SayHelloResponse retVal = ((ServiceConsumerHello.HelloService.HelloWorldSoap)(this)).SayHello(inValue);
            return retVal.Body.SayHelloResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceConsumerHello.HelloService.SayHelloResponse> ServiceConsumerHello.HelloService.HelloWorldSoap.SayHelloAsync(ServiceConsumerHello.HelloService.SayHelloRequest request) {
            return base.Channel.SayHelloAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceConsumerHello.HelloService.SayHelloResponse> SayHelloAsync(string name) {
            ServiceConsumerHello.HelloService.SayHelloRequest inValue = new ServiceConsumerHello.HelloService.SayHelloRequest();
            inValue.Body = new ServiceConsumerHello.HelloService.SayHelloRequestBody();
            inValue.Body.name = name;
            return ((ServiceConsumerHello.HelloService.HelloWorldSoap)(this)).SayHelloAsync(inValue);
        }
    }
}
